#!/bin/bash
#
# Copyright (c) 2011 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


readonly SCRIPT_DIR="$(dirname "$0")"
readonly SCRIPT_DIR_ABS="$(cd "${SCRIPT_DIR}" ; pwd -P)"

export NACL_TARGET_PLATFORM="$(basename $NACL_SDK_ROOT)"
export NACL_SDK_ROOT="$(dirname $NACL_SDK_ROOT)"

scons --file=build.scons --site-dir=$SCRIPT_DIR/nacl_sdk_scons "$*"
